spring:
  config:
    import: optional:secrets.yaml
  jpa:
    hibernate:
      ddl-auto: validate

  flyway:
    enabled: true
    baseline-on-migrate: true

  mail:
    host: smtp.gmail.com
    port: 587
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

logging:
  level:
    root: INFO
    io.github.ismaele77.liveminds: DEBUG
  file:
    name: application.log
    max-history: 1
    max-size: 10MB
    clean-history-on-start: true
