spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/geo
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
geolocation:
  api:
    key: "pk.16282d72a8dae89dd154ff91f9b934d3"
    url: "https://us1.locationiq.com/v1/search/structured"